name: Push File

on:
  push:
    paths:
      - 'Blog/**'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'Blog'
        destination_repo: 'wjianbo/blog-data'
        destination_branch: 'main'
        destination_folder: 'content'
        user_email: 'jnb.wang@gmail.com'
        user_name: 'jianbo'
        commit_msg: '[GHA] Update blog contents.'
